### ISSUE TITLE
Link in DOI

### ISSUE THREAD

**Issue by eovallemagallanes** [jp-um/university_of_malta_LaTeX_dissertation_template#12]
Can you help me with this? How can I add the link to the DOI in the references? It only appears for the references with URL

**Comment by jp-um** [comment]
Sorry for the delay in getting back to you (I did not have notifications switched on for this repo (doh!).

If I understand you correctly, this should be fixed with the natbib to biblatex conversion in the latest release. Of course, your bibtex entries will require a doi entry, e.g. `doi = {10.1021/ci2004658}`. 

Let me know if this does not fix it for you.
