### ISSUE TITLE
Odd right margin beginning from list of tables

### ISSUE THREAD

**Issue by Aonnghus** [jp-um/university_of_malta_LaTeX_dissertation_template#15]
Hello
First of all, thank you for this very nice template.
I cloned the repo on my machine and compiled the pdf with latexmk. Everything runs well, but when opening the pdf file, I remarked a weird margin on all titles starting from the one of the List of Tables.

![image](https://github.com/user-attachments/assets/2062ef64-17ec-4d32-87c1-5e134d0fdcbf)
![image](https://github.com/user-attachments/assets/d39a3685-dc50-4055-8a83-c96bd703970e)

This behaviour is not present on the previous pages:

![image](https://github.com/user-attachments/assets/ba4baa46-679c-4802-b798-676fdc26c216)

What could be the problem here?

**Comment by jp-um** [comment]
Sorry for the delay in getting back to you (I did not have notifications switched on for this repo (doh!).

This is by design (see an [example](https://tex.stackexchange.com/questions/357570/memoir-class-modify-ell-chapter-style)).  You can change chapter styles by changing `\chapterstyle{ell}` in `um.cls` (possible values as comments right before the statement).

`ell` is the default in memoir the memoir class (which `um` is based upon).
